# change the followings to match your Github username and repo name
baseurl: "https://luisnatera.com" # the name of your github repo
url: "https://luisnatera.com" # the url of your github pages
imgsurl: "https://luisnatera.com/assets/img/"

# site information used in page title, meta data etc.
title: "Luis Natera, Ph.D."
description: Network Scientist

# color theme for links
theme-color: stone # indigo|yellow|pink|green|stone|

# homepage information
author: Luis Natera, Ph.D.
author-bio: Network Scientist # change to false to hide
author-image: profile.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: True

collections:
  projects:
    output: true

nav-menu:
  #- text: Bitcoin
  #permalink: bitcoin
- text: About
  permalink: about
- text: Blog
  permalink: blog
- text: Projects
  permalink: projects

# use false to turn off any social media links
twitter: https://twitter.com/natera
facebook: false
instagram: false
github: https://github.com/nateraluis
linkedin: https://linkedin.com/in/natera
medium: false
google-scholar: https://scholar.google.com/citations?user=jZLYL_IAAAAJ&hl=nl&oi=ao
email: mailto:natera@hey.com

# footer information
footer-msg: false
footer-msg-link: https://github.com/harrywang/tailpages


# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
    - jekyll-analytics

jekyll_analytics:
  Plausible:
    domain: 'luisnatera.com'
    source: "https://plausible.io/js/plausible.js"
