# change the followings to match your Github username and repo name
baseurl: "https://luisnatera.com" # the name of your github repo
url: "https://luisnatera.com" # the url of your github pages

# site information used in page title, meta data etc.
title: "Luis Natera, Ph.D."
description: Network Scientist

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Luis Natera, Ph.D.
author-bio: Network Scientist & Data Analyst  # change to false to hide
author-image: profile.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: false

nav-menu:
  #- text: About
  #permalink: about
  #- text: Bitcoin
  #permalink: bitcoin
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: https://twitter.com/natera
facebook: false
instagram: false
github: https://github.com/nateraluis
linkedin: https://linkedin.com/in/natera
medium: false
google-scholar: https://scholar.google.com/citations?user=jZLYL_IAAAAJ&hl=nl&oi=ao
email: mailto:natera@hey.com

# footer information
footer-msg: false
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
